name: Run tests

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Get repositories
        run: sudo apt-get update
      - name: Install valgrind
        run: sudo apt-get install -y valgrind
      - name: Install commons
        run: git clone https://github.com/sisoputnfrba/so-commons-library.git && cd so-commons-library && sudo make install && cd ..
      - name: Run tests
        run: bash run-test.sh github ${GITHUB_REF#refs/heads/} ${GITHUB_SHA}

