name: Run clang-format Linter

on: [push, pull_request]

jobs:
  run_valgrind:
    runs-on: ubuntu-latest
    steps:
      - name: Perform tests
        uses: crisszkutnik/SO-valgrind-action@v1.2

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        extensions: 'h,cpp,c'
        clangFormatVersion: 11
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: Clang Formatter
        author_email: robot@example.com
        message: 'Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
